// ui/react/ProgressBar.tsx
/** React progress bar mirroring the Vue component's markup and ARIA semantics. */

/** Overlay modal with a progress track/fill, optional header and label nodes. */
export const ProgressBar = ({
   percent,
   label,
   showStatus = true,
   header,
   footer,
   panelClass,
   fillClass,
}: ReactProgressBarProps) => (
   <div className="fs-ehr-overlay">
      <div className={`fs-ehr-panel${panelClass ? ` ${panelClass}` : ""}`}>
         {header ? <div className="fs-ehr-header">{header}</div> : null}
         <div
            className="fs-ehr-track"
            role="progressbar"
            aria-valuenow={Math.round(percent)}
            aria-valuemin={0}
            aria-valuemax={100}
         >
            <div
               className={`fs-ehr-fill${fillClass ? ` ${fillClass}` : ""}`}
               style={{ width: `${percent}%` }}
            />
         </div>
         {showStatus ? <div className="fs-ehr-label">{label ?? "Loading…"}</div> : null}
         {footer}
      </div>
   </div>
)

// ui/vue/ProgressBar.vue
<template>
   <div class="fs-ehr-overlay">
      <div class="fs-ehr-panel" :class="panelClass">
         <div v-if="$slots.header" class="fs-ehr-header">
            <slot name="header" />
         </div>
         <div
            class="fs-ehr-track"
            role="progressbar"
            :aria-valuenow="Math.round(percent)"
            aria-valuemin="0"
            aria-valuemax="100"
         >
            <div class="fs-ehr-fill" :class="fillClass" :style="{ width: `${percent}%` }" />
         </div>
         <div v-if="showStatus" class="fs-ehr-label">
            <slot name="label">{{ label ?? "Loading…" }}</slot>
         </div>
         <slot name="footer" />
      </div>
   </div>
</template>

<script setup lang="ts">
withDefaults(
   defineProps<{
      percent: number
      label?: string
      showStatus?: boolean
      panelClass?: string
      fillClass?: string
   }>(),
   { showStatus: true })
</script>
